# GitHub Action
# MSI-B360-Catalina-EFI

name: Update README

on:
  push:
    paths:
      - "ReleaseTag"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Update README
        run: |
          chmod +x .github/workflows/update-readme.sh
          .github/workflows/update-readme.sh

      - name: Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update README.md"
          git push -v --progress
